[package]
name = "bureau"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.6.0"
crossbeam-skiplist = "0.1.3"
futures = { version = "0.3.30", features = ["thread-pool"] }
ouroboros = "0.18.4"
tokio = { version = "1.37.0", features = ["full", "tracing"] }
tokio-stream = { version = "0.1.15", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "ansi", "env-filter", "tracing-log"] }
